### ISSUE TITLE
Picture not loading

### ISSUE THREAD

**Issue by tamojit-123** [tamojit-123/developerPortfolio#3]
![Untitled design](https://user-images.githubusercontent.com/40804626/106268965-d88e2780-6251-11eb-8a4e-3a85dbf5c342.png)

**Comment by tamojit-123** [comment]
![Untitled design](https://user-images.githubusercontent.com/40804626/106269537-a0d3af80-6252-11eb-9a2e-69a6b2a2f822.gif)

**Comment by tamojit-123** [comment]
@all-contributors please add @tamojit-123 for code, design, doc, maintenance, blog

**Comment by tamojit-123** [comment]
@all-contributors please add @ImgBotApp for review, tools

**Comment by rattlecoder123** [comment]
the @all-contributors bot 🤖

**Comment by tamojit-123** [comment]
@all-contributors please add @rattlecoder123  for doc

**Comment by tamojit-123** [comment]
![Screenshot 2021-02-01 151856](https://user-images.githubusercontent.com/40804626/106442407-3fede680-64a1-11eb-9526-be1f166b6e00.png)
![Screenshot 2021-02-01 151921](https://user-images.githubusercontent.com/40804626/106442410-411f1380-64a1-11eb-829f-49b12e6bbd7a.png)

**Comment by tamojit-123** [comment]
![customer](https://user-images.githubusercontent.com/40804626/110212893-8e890900-7ec3-11eb-8043-5757f5cf69f6.png)

**Comment by tamojit-123** [comment]
![1557596028224](https://user-images.githubusercontent.com/40804626/117000956-6b31dd00-acff-11eb-95f7-d05b39e8d261.png)

**Comment by tamojit-123** [comment]
![Yeqk-unscreen](https://user-images.githubusercontent.com/40804626/122684179-92962800-d221-11eb-850d-6b7699c6f989.gif)

**Comment by tamojit-123** [comment]
![image8-2](https://user-images.githubusercontent.com/40804626/122684236-db4de100-d221-11eb-849c-d4604afec36d.jpg)

**Comment by tamojit-123** [comment]
<img width="960" alt="GLITCH" src="https://user-images.githubusercontent.com/40804626/127196612-6144f5f5-61e7-4031-9231-a34c04d6429e.png">
