### ISSUE TITLE
project location.

### ISSUE THREAD

**Issue by staminna** [tamojit-123/developerPortfolio#4]
Hi

Where is the project installed after running this command?

`$ docker build -t developerfolio:latest .
`
The second command after this is looking for location that does not exist:

$ docker run -t -p 3000:3000 developerfolio:latest
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/me/app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/jorge/app/package.json'

**Comment by tamojit-123** [comment]
@staminna for now, use node.

**Comment by tamojit-123** [comment]
@staminna Issue resolved
**Updated Docker build command:** 
```BASH
1) BUILD IMAGE : docker build -t developersportfolio:latest .
2) RUN IMAGE : docker run -t -p 3000:3000 developersportfolio:latest
```
docker: https://hub.docker.com/r/9123780018/developersportfolio
